### Updates an existing patient entity (Eminem)
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Marshall Bruce Mathers III - Slim Shady",
  "email": "eminem@raplegends.com",
  "address": "8 Mile Rd, Detroit, MI",
  "dateOfBirth": "1972-10-17"
}

###